2 notebooks (issues #54 e #52)
okfn-brasil/censo-querido-diario pull request #75
Opened 2021-03-08 00:18 UTC by faustost

- Ofereço esses dois notebooks em python como contribuição para as issues #54 e #52.
- A análise dos domínios comuns (issue #54) foi feita com base no notebook que já havia sido disponibilizado pela @anapaulagomes. Eu havia enviado essa mesma análise para a @ArianeCamilo há alguns dias via Telegram, eu apenas acrescentei 3 visualizações nesta versão que segue agora.
- Com relação à análise dos formatos, peço atenção especial à minha interpretação dos dados / análise qualitativa, pois eu não tenho certeza sobre a conveniência de cada formato, embora tenha feito algumas considerações a respeito.
- Por fim, reitero que esse tipo de trabalho é novo pra mim, então é importante um olhar crítico sobre as contribuições. De qualquer forma, agradeço muito a oportunidade. Espero poder contribuir novamente. 
Att,
Fausto.

2021-04-02 03:10 UTC, giuliocc requested changes
Oi Fausto!

Mil desculpas pela demora no seu review, esse mês foi bem corrido :/

Suas análises estão muito muito bem feitas e deu pra ver que deu bastante atenção em como o relatório iria ser lido. Muito legal ;) Tenho umas besteirinhas pra comentar, tomara que compense o tempo de espera, hehe. Vou deixar esse comentário aqui pra coisas mais gerais e comentários específicos em cada análise.

Agora que estou mais livre, me disponibilizo pra ajudar com o que for necessário e se no momento tu estiver sem tempo pode avisar também que é tranquilo :)

---

**Correção besta**: poderia mover os notebooks pra pasta `notebooks`?

Umas **dicas** (nada que a gente precise mexer agora, mas se achar que faz sentido pode ficar ainda melhor numa próxima):
- muitos dos comentários no meio do código poderiam virar células de texto, acho que aproveitar essa possibilidade em notebooks faz muito sentido e facilita criar o "storytelling"
- ao contar a estória, vê se não ficaria melhor colocar as conclusões de cada "pergunta" depois de fazer a análise e mostrar os dados, pra dar sequência na "apresentação"
- as tabelas geradas poderiam ser exportadas como csvs quando o notebook fosse executado, ficaria bem fácil de executar e usar depois

2021-04-02 03:10 UTC, giuliocc commented on 2021-03-01-faustosateles-file-types.ipynb
> +{
Na pergunta por estado, acho que vale mencionar que AC, AL, MA, PB, PI, RN e RR também disponibilizam 100% PDF texto

2021-04-02 03:10 UTC, giuliocc commented on 2021-03-01-faustosateles-file-types.ipynb
> +{
E os elogios :)

Sobre o código e conteúdo, faço os mesmos comentários que fiz na outra análise. E nessa deu pra ver claramente o que você observou sobre a correlação do PDF Texto com lugares mais populosos e os formatos alternativos correlacionado inversamente.

2021-04-05 17:44 UTC, faustost commented on 2021-03-01-faustosateles-common-domains.ipynb
> +{
Olá, @giuliocc! Muito obrigado pelos comentários. São muito pertinentes. Vou tentar trabalhar nessas modificações ao longo desta primeira quinzena de abril e, qualquer coisa, peço sua ajuda. Pode ser? 

Obs: é pra eu responder por aqui mesmo? Ainda não entendo da "etiqueta" nesse ambiente aqui kkkkk

abraço.
att,
Fausto.

2021-04-06 00:37 UTC, giuliocc commented on 2021-03-01-faustosateles-common-domains.ipynb
> +{
Massa, @faustost! Tranquilepa :)

Primeira quinzena de abril funciona perfeitamente. E pode chamar lá no discord por qualquer motivo que seja.

---

Sobre a etiqueta: 

Primeiro, fica livre pra responder como quiser ou onde quiser :) Estressa muito não que com o tempo pega o jeito. Mas se quiser uma dicas sobre github posso te mandar depois. Mantendo o papo aqui transparente pra quem quiser entender o que foi discutido depois tá de boa. Minha impressão é que só começa a ficar ruim quando tem excesso de assuntos fora do tópico ou então muita coisa decidida em outros meios e não mencionado aqui acaba não ficando transparente pra quem quiser entender depois.

2021-04-11 13:51 UTC, faustost commented
Faaala, @giuliocc ! Enviei 3 novos commits (deletei os notebooks que estavam na pasta errada, e enviei as versões atualizadas).
Atualizações:
1. Tentei reorganizar os "story telling" colocando as perguntas antes dos códigos e as respostas depois.
2. Na análise de formatos de arquivo, mencionei os estados que faltavam com 100% de PDF texto e deixei claro que os percentuais excluem da contagem os municípios sem dados de formato.
3. Na análise de domínios compartilhados, acrescentei aqueles que estavam nas colunas fonte_2 a fonte_4. Fez bastante diferença. Muito importante você ter apontado.
4. Ordenei algumas tabelas e gráficos e outras bobeiras do tipo.

Espero ter conseguido atender às suas considerações. Grande abraço!

2021-04-14 05:43 UTC, giuliocc commented
Massa, @faustost ! Ficou sensacional, parabéns :):)

Dei umas modificadas bestas nos textos. Me diz o que tu achou? Acho que a parte mais relevante das modificações que fiz foi nas duas últimas perguntas da análise de domínios. Ali acho que com a informação que temos não dá pra dizer quantos são os domínios exclusivos de um município e quantos são compartilhados. Se um município pode publicar em vários domínios, então os percentuais não iriam ser os mesmos com isso ocorrendo, certo? Se eu tiver viajando me avisa, por favor :) Assim eu deixei o texto mais genérico pra indicar apenas quantos municípios compartilham quantos domínios em cada UF e região.

Abraço!

2021-04-14 14:26 UTC, faustost commented
De acordo, @giuliocc. Você está correto, pode acontecer sim, seu texto está mais aderente ao limite do que os dados nos dizem.
Obrigado pela revisão e pela ajuda!!
Abraço.

2021-04-19 02:48 UTC, giuliocc approved these changes
Fausto, estou deixando aprovado este PR por enquanto. Mas a Ariane ainda vai dar uma olhada antes de ser mesclado, beleza?

Muito obrigado pela contribuição :) Ajudou muito mais do que você pode imaginar!

2021-05-19 14:01 UTC, merged