Add get-data view and button
okfn-brasil/censo-querido-diario pull request #9
Opened 2020-10-06 04:31 UTC by vantonini

It implements a function that allow an user to download the data about what was already done. One can download only cities that have already been mapped or an user can download a list with all cities and those without any kind of information will come with empty columns. 

NOTE: the way it's implemented, cities that starts with an accent on the first letter will be in end of the file.

2020-10-14 17:18 UTC, sergiomario requested changes

2020-10-14 17:18 UTC, sergiomario commented on formulario/templates/mapped_cities.html
> +    {% if context == 'Brasil' %}
Pode jogar todo esse `if` para a linha 83, assim ficará dentro do alert verde.

2020-10-14 17:18 UTC, sergiomario commented on formulario/templates/mapped_cities.html
> +    <div class="col-sm-10">
Pode remover essa classe: `class="col-sm-10"`. Assim ficará alinhado centralmente dentro do alert.

2020-10-14 17:18 UTC, sergiomario commented on formulario/templates/mapped_cities.html
> +        <button type="submit" class="btn btn-primary">Baixar Dados</button>
Sugiro alterar o botão para a classe CSS que a @ArianeCamilo criou já no vovo layout:
```
<button type="submit" class="btn btn-region">Baixar Dados</button>
```

2020-10-14 17:18 UTC, sergiomario commented on formulario/views.py
> +                None,
Eu sigiro remover todos esses valores em `None`, assim:
`lista.append([smart_str(municipio.municipio)])`

2020-10-14 17:20 UTC, sergiomario requested changes

2020-10-14 17:20 UTC, sergiomario commented on formulario/views.py
> +            smart_str(municipio.municipio),
Sugiro inserir os campos do objeto municipio também:
```
lista.append([
            smart_str(municipio.municipio),
            smart_str(municipio.municipio.ibge),
            smart_str(municipio.municipio.ibge7),
            smart_str(municipio.municipio.uf),
            smart_str(municipio.municipio.regiao),
            smart_str(municipio.municipio.populacao_2010),
            smart_str(municipio.municipio.capital),
            smart_str(municipio.fonte_1),
            smart_str(municipio.fonte_2),
            smart_str(municipio.fonte_3),
            smart_str(municipio.fonte_4),
            smart_str(municipio.is_online),
            smart_str(municipio.data_inicial),
            smart_str(municipio.get_tipo_arquivo_display()),
            smart_str(municipio.validacao),
            smart_str(municipio.navegacao),
            smart_str(municipio.observacoes),
        ])
```

2020-10-19 01:29 UTC, vantonini commented on formulario/views.py
> +            smart_str(municipio.municipio),
feito!

2020-10-19 01:29 UTC, vantonini commented on formulario/templates/mapped_cities.html
> +        <button type="submit" class="btn btn-primary">Baixar Dados</button>
Feito

2020-10-19 01:30 UTC, vantonini commented on formulario/templates/mapped_cities.html
> +    {% if context == 'Brasil' %}
Se eu entendi direito, esta feito tb

2020-10-19 01:31 UTC, vantonini commented
@sergiomario fiz as alteracoes e arrumei o sort antes de exportar.

2020-10-19 01:35 UTC, sergiomario approved these changes
LGTM

2020-10-19 01:35 UTC, merged